// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessPaymentDataLayer.Contexts;

namespace PaymentProcess.DataLayer.Migrations
{
    [DbContext(typeof(ProcessPaymentContext))]
    partial class ProcessPaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessPaymentDataLayer.DomainObjects.PaymentDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("CardHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ProcessPaymentDataLayer.DomainObjects.RequestStatusDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentDoId")
                        .HasColumnType("int");

                    b.Property<int>("requestSates")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDoId")
                        .IsUnique();

                    b.ToTable("RequestStatus");
                });

            modelBuilder.Entity("ProcessPaymentDataLayer.DomainObjects.RequestStatusDo", b =>
                {
                    b.HasOne("ProcessPaymentDataLayer.DomainObjects.PaymentDo", "PaymentDo")
                        .WithOne("requestStatus")
                        .HasForeignKey("ProcessPaymentDataLayer.DomainObjects.RequestStatusDo", "PaymentDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentDo");
                });

            modelBuilder.Entity("ProcessPaymentDataLayer.DomainObjects.PaymentDo", b =>
                {
                    b.Navigation("requestStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
